// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fran.programacion2.trabajofinal.domain;

import fran.programacion2.trabajofinal.domain.Hashtag;
import fran.programacion2.trabajofinal.domain.HashtagDataOnDemand;
import fran.programacion2.trabajofinal.domain.Mensaje;
import fran.programacion2.trabajofinal.domain.MensajeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect HashtagDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HashtagDataOnDemand: @Component;
    
    private Random HashtagDataOnDemand.rnd = new SecureRandom();
    
    private List<Hashtag> HashtagDataOnDemand.data;
    
    @Autowired
    MensajeDataOnDemand HashtagDataOnDemand.mensajeDataOnDemand;
    
    public Hashtag HashtagDataOnDemand.getNewTransientHashtag(int index) {
        Hashtag obj = new Hashtag();
        setHash(obj, index);
        setIdMensaje(obj, index);
        return obj;
    }
    
    public void HashtagDataOnDemand.setHash(Hashtag obj, int index) {
        String hash = "hash_" + index;
        obj.setHash(hash);
    }
    
    public void HashtagDataOnDemand.setIdMensaje(Hashtag obj, int index) {
        Mensaje idMensaje = mensajeDataOnDemand.getRandomMensaje();
        obj.setIdMensaje(idMensaje);
    }
    
    public Hashtag HashtagDataOnDemand.getSpecificHashtag(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Hashtag obj = data.get(index);
        Long id = obj.getId();
        return Hashtag.findHashtag(id);
    }
    
    public Hashtag HashtagDataOnDemand.getRandomHashtag() {
        init();
        Hashtag obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Hashtag.findHashtag(id);
    }
    
    public boolean HashtagDataOnDemand.modifyHashtag(Hashtag obj) {
        return false;
    }
    
    public void HashtagDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Hashtag.findHashtagEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Hashtag' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Hashtag>();
        for (int i = 0; i < 10; i++) {
            Hashtag obj = getNewTransientHashtag(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
