// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fran.programacion2.trabajofinal.domain;

import fran.programacion2.trabajofinal.domain.Hashtag;
import fran.programacion2.trabajofinal.domain.HashtagDataOnDemand;
import fran.programacion2.trabajofinal.domain.HashtagIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HashtagIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HashtagIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HashtagIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HashtagIntegrationTest: @Transactional;
    
    @Autowired
    HashtagDataOnDemand HashtagIntegrationTest.dod;
    
    @Test
    public void HashtagIntegrationTest.testCountHashtags() {
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", dod.getRandomHashtag());
        long count = Hashtag.countHashtags();
        Assert.assertTrue("Counter for 'Hashtag' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HashtagIntegrationTest.testFindHashtag() {
        Hashtag obj = dod.getRandomHashtag();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to provide an identifier", id);
        obj = Hashtag.findHashtag(id);
        Assert.assertNotNull("Find method for 'Hashtag' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Hashtag' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HashtagIntegrationTest.testFindAllHashtags() {
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", dod.getRandomHashtag());
        long count = Hashtag.countHashtags();
        Assert.assertTrue("Too expensive to perform a find all test for 'Hashtag', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Hashtag> result = Hashtag.findAllHashtags();
        Assert.assertNotNull("Find all method for 'Hashtag' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Hashtag' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HashtagIntegrationTest.testFindHashtagEntries() {
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", dod.getRandomHashtag());
        long count = Hashtag.countHashtags();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Hashtag> result = Hashtag.findHashtagEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Hashtag' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Hashtag' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HashtagIntegrationTest.testFlush() {
        Hashtag obj = dod.getRandomHashtag();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to provide an identifier", id);
        obj = Hashtag.findHashtag(id);
        Assert.assertNotNull("Find method for 'Hashtag' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHashtag(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Hashtag' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HashtagIntegrationTest.testMergeUpdate() {
        Hashtag obj = dod.getRandomHashtag();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to provide an identifier", id);
        obj = Hashtag.findHashtag(id);
        boolean modified =  dod.modifyHashtag(obj);
        Integer currentVersion = obj.getVersion();
        Hashtag merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Hashtag' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HashtagIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", dod.getRandomHashtag());
        Hashtag obj = dod.getNewTransientHashtag(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Hashtag' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Hashtag' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HashtagIntegrationTest.testRemove() {
        Hashtag obj = dod.getRandomHashtag();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hashtag' failed to provide an identifier", id);
        obj = Hashtag.findHashtag(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Hashtag' with identifier '" + id + "'", Hashtag.findHashtag(id));
    }
    
}
