// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fran.programacion2.trabajofinal.domain;

import fran.programacion2.trabajofinal.domain.Mensaje;
import fran.programacion2.trabajofinal.domain.MensajeDataOnDemand;
import fran.programacion2.trabajofinal.domain.User;
import fran.programacion2.trabajofinal.domain.UserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MensajeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MensajeDataOnDemand: @Component;
    
    private Random MensajeDataOnDemand.rnd = new SecureRandom();
    
    private List<Mensaje> MensajeDataOnDemand.data;
    
    @Autowired
    UserDataOnDemand MensajeDataOnDemand.userDataOnDemand;
    
    public Mensaje MensajeDataOnDemand.getNewTransientMensaje(int index) {
        Mensaje obj = new Mensaje();
        setAutor(obj, index);
        setAutorOriginal(obj, index);
        setFecha(obj, index);
        setFechaPublicacion(obj, index);
        setTexto(obj, index);
        return obj;
    }
    
    public void MensajeDataOnDemand.setAutor(Mensaje obj, int index) {
        User autor = userDataOnDemand.getRandomUser();
        obj.setAutor(autor);
    }
    
    public void MensajeDataOnDemand.setAutorOriginal(Mensaje obj, int index) {
        String autorOriginal = "autorOriginal_" + index;
        obj.setAutorOriginal(autorOriginal);
    }
    
    public void MensajeDataOnDemand.setFecha(Mensaje obj, int index) {
        String fecha = "fecha_" + index;
        obj.setFecha(fecha);
    }
    
    public void MensajeDataOnDemand.setFechaPublicacion(Mensaje obj, int index) {
        Date fechaPublicacion = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setFechaPublicacion(fechaPublicacion);
    }
    
    public void MensajeDataOnDemand.setTexto(Mensaje obj, int index) {
        String texto = "texto_" + index;
        if (texto.length() > 140) {
            texto = texto.substring(0, 140);
        }
        obj.setTexto(texto);
    }
    
    public Mensaje MensajeDataOnDemand.getSpecificMensaje(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Mensaje obj = data.get(index);
        Long id = obj.getId();
        return Mensaje.findMensaje(id);
    }
    
    public Mensaje MensajeDataOnDemand.getRandomMensaje() {
        init();
        Mensaje obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Mensaje.findMensaje(id);
    }
    
    public boolean MensajeDataOnDemand.modifyMensaje(Mensaje obj) {
        return false;
    }
    
    public void MensajeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Mensaje.findMensajeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Mensaje' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Mensaje>();
        for (int i = 0; i < 10; i++) {
            Mensaje obj = getNewTransientMensaje(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
