// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fran.programacion2.trabajofinal.domain;

import fran.programacion2.trabajofinal.domain.Mensaje;
import fran.programacion2.trabajofinal.domain.MensajeDataOnDemand;
import fran.programacion2.trabajofinal.domain.Referencia;
import fran.programacion2.trabajofinal.domain.ReferenciaDataOnDemand;
import fran.programacion2.trabajofinal.domain.User;
import fran.programacion2.trabajofinal.domain.UserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReferenciaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReferenciaDataOnDemand: @Component;
    
    private Random ReferenciaDataOnDemand.rnd = new SecureRandom();
    
    private List<Referencia> ReferenciaDataOnDemand.data;
    
    @Autowired
    MensajeDataOnDemand ReferenciaDataOnDemand.mensajeDataOnDemand;
    
    @Autowired
    UserDataOnDemand ReferenciaDataOnDemand.userDataOnDemand;
    
    public Referencia ReferenciaDataOnDemand.getNewTransientReferencia(int index) {
        Referencia obj = new Referencia();
        setIdMensaje(obj, index);
        setReferido(obj, index);
        return obj;
    }
    
    public void ReferenciaDataOnDemand.setIdMensaje(Referencia obj, int index) {
        Mensaje idMensaje = mensajeDataOnDemand.getRandomMensaje();
        obj.setIdMensaje(idMensaje);
    }
    
    public void ReferenciaDataOnDemand.setReferido(Referencia obj, int index) {
        User referido = userDataOnDemand.getRandomUser();
        obj.setReferido(referido);
    }
    
    public Referencia ReferenciaDataOnDemand.getSpecificReferencia(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Referencia obj = data.get(index);
        Long id = obj.getId();
        return Referencia.findReferencia(id);
    }
    
    public Referencia ReferenciaDataOnDemand.getRandomReferencia() {
        init();
        Referencia obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Referencia.findReferencia(id);
    }
    
    public boolean ReferenciaDataOnDemand.modifyReferencia(Referencia obj) {
        return false;
    }
    
    public void ReferenciaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Referencia.findReferenciaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Referencia' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Referencia>();
        for (int i = 0; i < 10; i++) {
            Referencia obj = getNewTransientReferencia(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
