// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fran.programacion2.trabajofinal.domain;

import fran.programacion2.trabajofinal.domain.Referencia;
import fran.programacion2.trabajofinal.domain.ReferenciaDataOnDemand;
import fran.programacion2.trabajofinal.domain.ReferenciaIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReferenciaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReferenciaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReferenciaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReferenciaIntegrationTest: @Transactional;
    
    @Autowired
    ReferenciaDataOnDemand ReferenciaIntegrationTest.dod;
    
    @Test
    public void ReferenciaIntegrationTest.testCountReferencias() {
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", dod.getRandomReferencia());
        long count = Referencia.countReferencias();
        Assert.assertTrue("Counter for 'Referencia' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReferenciaIntegrationTest.testFindReferencia() {
        Referencia obj = dod.getRandomReferencia();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to provide an identifier", id);
        obj = Referencia.findReferencia(id);
        Assert.assertNotNull("Find method for 'Referencia' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Referencia' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReferenciaIntegrationTest.testFindAllReferencias() {
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", dod.getRandomReferencia());
        long count = Referencia.countReferencias();
        Assert.assertTrue("Too expensive to perform a find all test for 'Referencia', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Referencia> result = Referencia.findAllReferencias();
        Assert.assertNotNull("Find all method for 'Referencia' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Referencia' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReferenciaIntegrationTest.testFindReferenciaEntries() {
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", dod.getRandomReferencia());
        long count = Referencia.countReferencias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Referencia> result = Referencia.findReferenciaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Referencia' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Referencia' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReferenciaIntegrationTest.testFlush() {
        Referencia obj = dod.getRandomReferencia();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to provide an identifier", id);
        obj = Referencia.findReferencia(id);
        Assert.assertNotNull("Find method for 'Referencia' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReferencia(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Referencia' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReferenciaIntegrationTest.testMergeUpdate() {
        Referencia obj = dod.getRandomReferencia();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to provide an identifier", id);
        obj = Referencia.findReferencia(id);
        boolean modified =  dod.modifyReferencia(obj);
        Integer currentVersion = obj.getVersion();
        Referencia merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Referencia' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReferenciaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", dod.getRandomReferencia());
        Referencia obj = dod.getNewTransientReferencia(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Referencia' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Referencia' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Referencia' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReferenciaIntegrationTest.testRemove() {
        Referencia obj = dod.getRandomReferencia();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Referencia' failed to provide an identifier", id);
        obj = Referencia.findReferencia(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Referencia' with identifier '" + id + "'", Referencia.findReferencia(id));
    }
    
}
