// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fran.programacion2.trabajofinal.domain;

import fran.programacion2.trabajofinal.domain.SeguidoresSeguidos;
import fran.programacion2.trabajofinal.domain.SeguidoresSeguidosDataOnDemand;
import fran.programacion2.trabajofinal.domain.User;
import fran.programacion2.trabajofinal.domain.UserDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SeguidoresSeguidosDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SeguidoresSeguidosDataOnDemand: @Component;
    
    private Random SeguidoresSeguidosDataOnDemand.rnd = new SecureRandom();
    
    private List<SeguidoresSeguidos> SeguidoresSeguidosDataOnDemand.data;
    
    @Autowired
    UserDataOnDemand SeguidoresSeguidosDataOnDemand.userDataOnDemand;
    
    public SeguidoresSeguidos SeguidoresSeguidosDataOnDemand.getNewTransientSeguidoresSeguidos(int index) {
        SeguidoresSeguidos obj = new SeguidoresSeguidos();
        setSeguido(obj, index);
        setSeguidor(obj, index);
        return obj;
    }
    
    public void SeguidoresSeguidosDataOnDemand.setSeguido(SeguidoresSeguidos obj, int index) {
        User seguido = userDataOnDemand.getRandomUser();
        obj.setSeguido(seguido);
    }
    
    public void SeguidoresSeguidosDataOnDemand.setSeguidor(SeguidoresSeguidos obj, int index) {
        User seguidor = userDataOnDemand.getRandomUser();
        obj.setSeguidor(seguidor);
    }
    
    public SeguidoresSeguidos SeguidoresSeguidosDataOnDemand.getSpecificSeguidoresSeguidos(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SeguidoresSeguidos obj = data.get(index);
        Long id = obj.getId();
        return SeguidoresSeguidos.findSeguidoresSeguidos(id);
    }
    
    public SeguidoresSeguidos SeguidoresSeguidosDataOnDemand.getRandomSeguidoresSeguidos() {
        init();
        SeguidoresSeguidos obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SeguidoresSeguidos.findSeguidoresSeguidos(id);
    }
    
    public boolean SeguidoresSeguidosDataOnDemand.modifySeguidoresSeguidos(SeguidoresSeguidos obj) {
        return false;
    }
    
    public void SeguidoresSeguidosDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SeguidoresSeguidos.findSeguidoresSeguidosEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SeguidoresSeguidos' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SeguidoresSeguidos>();
        for (int i = 0; i < 10; i++) {
            SeguidoresSeguidos obj = getNewTransientSeguidoresSeguidos(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
