// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fran.programacion2.trabajofinal.domain;

import fran.programacion2.trabajofinal.domain.SeguidoresSeguidos;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SeguidoresSeguidos_Roo_Configurable {
    
    declare @type: SeguidoresSeguidos: @Configurable;
    
}
